// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Open a repository: summarize it, persist + cache it, mark it active, and start
	 *  watching its `.git` dir for ambient change triggers.
	 */
	openRepository: (path: string) => typedError<RepoSummary, string>(__TAURI_INVOKE("open_repository", { path })),
	/**  Path of the currently active repository, if any. */
	currentRepo: () => typedError<string | null, string>(__TAURI_INVOKE("current_repo")),
	/**  Commits (with graph lanes) for the active repo — powers the Canvas timeline. */
	listCommits: (limit: number) => typedError<CommitInfo[], string>(__TAURI_INVOKE("list_commits", { limit })),
	/**  Local + remote branches for the active repo. */
	listBranches: () => typedError<BranchInfo[], string>(__TAURI_INVOKE("list_branches")),
	/**  Working-tree status for the active repo. */
	getStatus: () => typedError<RepoStatus, string>(__TAURI_INVOKE("get_status")),
	/**  Conflicted files in the active repo (Merge Conflict Editor data source). */
	listConflicts: () => typedError<ConflictHunk[], string>(__TAURI_INVOKE("list_conflicts")),
	/**  Apply a conflict resolution (stub in the scaffold). */
	resolveConflict: (file: string, resolution: string) => typedError<null, string>(__TAURI_INVOKE("resolve_conflict", { file, resolution })),
	/**  "Who Did What" contributor metrics for the active repo. */
	contributorStats: () => typedError<ContributorStat[], string>(__TAURI_INVOKE("contributor_stats")),
	/**
	 *  CI/CD + compliance badges for the active repo: real DCO from local commit trailers +
	 *  build/test from the GitHub Checks API (via `gh`). The poll is persisted to the local
	 *  cache with a real `updated_at` before returning.
	 */
	getCiStatus: () => typedError<CiStatus[], string>(__TAURI_INVOKE("get_ci_status")),
	/**  Read a persisted user-config value (custom filters, aliases, groupings, …). */
	getConfig: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_config", { key })),
	/**  Persist a user-config value. */
	setConfig: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_config", { key, value })),
};

/* Types */
/**  A local or remote branch reference. */
export type BranchInfo = {
	name: string,
	is_head: boolean,
	is_remote: boolean,
	/**  Hex OID the branch points at, if resolvable. */
	target: string | null,
};

export type CiStatus = {
	pipeline: string,
	/**
	 *  Canonical state the UI keys its icon off: `success`, `failed`, `running`,
	 *  `verified`, `unsigned`, or `unknown`.
	 */
	status: string,
	/**  Short badge label surfaced in the UI, e.g. `passing`, `compliant`, `3/4 signed`. */
	badge: string,
	/**  Unix epoch seconds of when this status was computed. */
	updated_at: number | null,
};

/**  A single commit, enriched with a `lane` index used by the Canvas timeline renderer. */
export type CommitInfo = {
	id: string,
	short_id: string,
	summary: string,
	body: string,
	author_name: string,
	author_email: string,
	/**  Author time, Unix epoch seconds. */
	timestamp: number | null,
	parent_ids: string[],
	/**  Horizontal lane assigned by the graph-layout pass (0-based). */
	lane: number,
};

/**  A conflicted file with its three-way sides (sides are placeholders in the scaffold). */
export type ConflictHunk = {
	file: string,
	ours: string,
	theirs: string,
	base: string,
};

export type ContributorStat = {
	author_name: string,
	author_email: string,
	commits: number,
	files_owned: number,
	reviews: number,
};

/**  Working-tree status for a single path. */
export type FileStatus = {
	path: string,
	/**  One of: `new`, `modified`, `deleted`, `renamed`, `typechange`, `conflicted`, `ignored`. */
	status: string,
	staged: boolean,
};

/**  Aggregate working-tree + HEAD status for the open repository. */
export type RepoStatus = {
	head_branch: string | null,
	files: FileStatus[],
	ahead: number,
	behind: number,
	has_conflicts: boolean,
};

/**  Lightweight summary returned when a repository is opened. */
export type RepoSummary = {
	path: string,
	head_branch: string | null,
	commit_count: number,
	branch_count: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

